name: create-sqs-queues
description: Create SQS Queues and Redrive Policy
author: DevOps Team

inputs:
  queueName:
    description: 'The name of the main queue'
    required: true
    default: 'my-queue.fifo'
  deadLetterQueueName:
    description: 'The name of the dead-letter queue'
    required: true
    default: 'my-queue-dl.fifo'
  queueRetentionPeriod:
    description: 'The message retention period for the main queue in seconds'
    required: false
    default: '259200'  # 3 days
  maxReceiveCount:
    description: 'The maximum number of times a message is received from the main queue before being moved to the dead-letter queue'
    required: false
    default: '4'

runs:
  using: 'composite'
  steps:
    - name: Provision SQS Queues and Redrive Policy
      shell: bash
      run: |
          set -e
          # Create dead-letter queue
          if ! aws sqs get-queue-url --queue-name "${{ inputs.deadLetterQueueName }}" >/dev/null 2>&1; then
            echo "Creating SQS Dead-Letter Queue '${{ inputs.deadLetterQueueName }}'"
            aws sqs create-queue --queue-name "${{ inputs.deadLetterQueueName }}" --attributes FifoQueue=true
            deadLetterQueueUrl=$(aws sqs get-queue-url --queue-name "${{ inputs.deadLetterQueueName }}") | jq -r '.QueueUrl'
            echo "SQS Dead-Letter Queue '${{ inputs.deadLetterQueueName }}' created. URL: ${deadLetterQueueUrl}"
          else
            echo "SQS Dead-Letter Queue '${{ inputs.deadLetterQueueName }}' already exists."
            deadLetterQueueUrl=$(aws sqs get-queue-url --queue-name "${{ inputs.deadLetterQueueName }}") | jq -r '.QueueUrl'
            echo "SQS Dead-Letter Queue '${{ inputs.deadLetterQueueName }}' URL: ${deadLetterQueueUrl}"
          fi

          # # Retrieve main and dead-letter queue URL

          # queueUrl=$(echo "${deadLetterQueueUrl}" | jq -r '.QueueUrl')
          # deadLetterQueueUrl=$(echo "${deadLetterQueueUrl}" | jq -r '.QueueUrl')

          # Retrieve dead-letter queue ARN
          deadLetterQueueArn=$(aws sqs get-queue-attributes --queue-url "${deadLetterQueueUrl}" --attribute-names QueueArn | jq -r '.Attributes.QueueArn')

          if [[ $(aws sqs list-queues --queue-name-prefix "${{ inputs.queueName }}") ]]; then
            echo "SQS Queue '${{ inputs.queueName }}' already exists"
            queueUrl=$(aws sqs get-queue-url --queue-name "${{ inputs.queueName }}") | jq -r '.QueueUrl'
          else
            echo "Creating SQS Queue '${{ inputs.queueName }}'"
            REDRIVE_POLICY=$(jq -n \
              --arg dlqa "${deadLetterQueueArn}" \
              --arg mrc "${{ inputs.maxReceiveCount }}" \
              '{deadLetterTargetArn: $dlqa, maxReceiveCount: $mrc}' | jq tostring)
            JSON_STRING=$(jq -n \
              --arg rp "${{ inputs.queueRetentionPeriod }}" \
              --arg rp "${REDRIVE_POLICY}" \
              '{RedrivePolicy: $rp, MessageRetentionPeriod: $rp, FifoQueue: "true"}' | jq tostring)
            aws sqs create-queue --queue-name "${{ inputs.queueName }}" --attributes "$JSON_STRING"
            echo "SQS Queue '${{ inputs.queueName }}' created successfully"
            queueUrl=$(aws sqs get-queue-url --queue-name "${{ inputs.queueName }}") | jq -r '.QueueUrl'
            echo "SQS Queue '${{ inputs.queueName }}' URL: ${queueUrl}"
          fi

          # Output queue URL and queue names
          echo "queueUrl=${queueUrl}" >> $GITHUB_ENV
          echo "queueName=${{ inputs.queueName }}" >> $GITHUB_ENV
          echo "deadLetterQueueUrl=${deadLetterQueueUrl}" >> $GITHUB_ENV
          echo "deadLetterQueueName=${{ inputs.deadLetterQueueName }}" >> $GITHUB_ENV